version: '3.1'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_MULTIPLE_DATABASES=simple_auth,simple_auth_test
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080